#!/usr/bin/env python3

import os
import glob
import envtpl
import sys
from mflog import get_logger
from mfutil.plugins import layerapi2_label_to_plugin_name
from configparser_extended import ExtendedConfigParser

MODULE_RUNTIME_HOME = os.environ["MODULE_RUNTIME_HOME"]
MFBASE_PLUGINS_HOME = os.path.join(MODULE_RUNTIME_HOME,
                                   "var", "plugins")
CONFIG = os.environ.get('MFCONFIG', 'GENERIC')
HOSTNAME = os.environ.get('MFCOM_HOSTNAME')
HOSTNAME_FULL = os.environ.get('MFCOM_HOSTNAME_FULL')
MODULE = os.environ['MODULE']

LOGGER = get_logger("__make_nginx_conf")


def get_conf(plugin_configuration_file):
    plugin_conf = {}
    plugin_directory = os.path.dirname(plugin_configuration_file)
    parser = ExtendedConfigParser(config=CONFIG, strict=False,
                                  inheritance='im', interpolation=None)
    try:
        with open(os.path.join(plugin_directory,
                               ".layerapi2_label"), "r") as f:
            label = f.read().strip()
    except Exception:
        LOGGER.warning(
            "can't read %s/.layerapi2_label => ignoring this plugin",
            plugin_directory)
        return None
    try:
        plugin_name = layerapi2_label_to_plugin_name(label)
    except Exception as e:
        LOGGER.warning("can't read %s/.layerapi2_label with error: %s => "
                       "ignoring this plugin", plugin_directory, e)
        return None
    plugin_conf['directory'] = plugin_directory
    plugin_conf['name'] = plugin_name
    parser.read(plugin_configuration_file)
    plugin_conf['use_postgresql'] = "1"
    if parser.has_option('general', 'use_postgresql'):
        if parser.getint("general", "use_postgresql") == 0:
            plugin_conf['use_postgresql'] = "0"
    plugin_conf['use_storage'] = "1"
    if parser.has_option('general', 'use_storage'):
        if parser.getint("general", "use_storage") == 0:
            plugin_conf['use_storage'] = "0"
    return plugin_conf


plugins = []
if len(sys.argv) == 2:
    config_files = glob.glob(sys.argv[1] + "/config.ini")
else:
    config_files = glob.glob(MFBASE_PLUGINS_HOME + "/*/config.ini")
for config_file in config_files:
    plugin_conf = get_conf(config_file)
    if plugin_conf:
        plugins.append(plugin_conf)

nginx_conf_file = os.path.join(os.environ['MODULE_HOME'], 'config',
                               'nginx.conf')

with open(nginx_conf_file, "r") as f:
    extra_variables = {
        "PLUGINS": plugins
    }
    content = envtpl.render_string(f.read(), extra_variables=extra_variables,
                                   keep_multi_blank_lines=False)

print(content)
