#!/bin/bash

cat "${MFMODULE_HOME}/config/postgresql.conf" |envtpl --reduce-multi-blank-lines >"${MFMODULE_RUNTIME_HOME}/tmp/config_auto/postgresql.conf"
if test -s "${MFMODULE_RUNTIME_HOME}/tmp/config_auto/postgresql.conf"; then
    exit 0
else
    exit 1
fi
