CONFIGS=config.ini postgresql.conf mflog_override.conf nginx.conf

include ../adm/root.mk
include $(MFEXT_HOME)/share/subdir_root.mk
include $(MFCOM_HOME)/share/config_subdir.mk

all:: $(MODULE_HOME)/config/telegraf.conf $(MODULE_HOME)/config/circus.ini
